version: '3.8'

services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - ./backend:/data
    environment:
      - TZ=America/Sao_Paulo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "80:80"  # Mudando para porta 80 do Nginx
    restart: always

